name: Auto Feature Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 mins
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Copilot CLI
      run: npm install -g @githubnext/copilot-cli

    - name: Login to Copilot
      run: echo "${{ secrets.COPILOT_AUTH }}" > ~/.copilot-auth && copilot auth login --token ${{ secrets.COPILOT_AUTH }}

    - name: Generate Feature from Request
      run: |
        FEATURE=$(head -n 1 feature-requests.txt)
        echo "Generating feature: $FEATURE"
        copilot suggest "$FEATURE"
        git config user.name "AI Bot"
        git config user.email "bot@example.com"
        git add .
        git commit -m "Implemented: $FEATURE" || echo "No changes"
        git push

    - name: Clear Processed Request
      run: |
        tail -n +2 feature-requests.txt > temp && mv temp feature-requests.txt
        git add feature-requests.txt
        git commit -m "Processed one request"
        git push

